"""
Critic Component for Kairo.

Evaluates whether the latest observation moved the task graph toward the goal.
If not, flags a 'no-progress' state with a detailed critique and actionable recommendation
to prevent silent infinite loops.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional

from orchestrator.observer import ObservationResult, ObservationFact

logger = logging.getLogger("orchestrator.critic")


@dataclass
class CritiqueResult:
    """
    Evaluation assessment generated by the Critic.
    """
    has_progress: bool
    status: str  # "progress" | "no_progress" | "blocked" | "failed"
    score: float  # 0.0 to 1.0 confidence in progress
    critique: str
    new_facts_count: int
    is_stagnant: bool
    is_circular: bool
    recommendation: str  # "advance" | "retry" | "switch_tool" | "fail"
    suggested_action: Optional[str] = None
    evaluated_node_id: Optional[str] = None
    evaluated_capability: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class Critic:
    """
    The Critic evaluates whether the latest observation from a tool execution
    advanced the task graph toward the overall security assessment goal.
    Detects stagnant, empty, or circular states and flags 'no-progress'.
    """

    def evaluate(
        self,
        node: Dict[str, Any],
        plan_goal: str,
        observation: ObservationResult | Dict[str, Any],
        previous_observations: Optional[List[Dict[str, Any]]] = None,
        attempt_number: int = 1,
    ) -> CritiqueResult:
        previous_observations = previous_observations or []
        node_id = node.get("node_id", "unknown")
        capability = node.get("capability", "").lower()
        tool_id = node.get("assigned_tool", "")

        # Unpack observation if passed as Dict
        if isinstance(observation, dict):
            obs_status = observation.get("status", "unknown")
            exit_code = observation.get("exit_code", 0)
            has_findings = observation.get("has_findings", False)
            is_empty = observation.get("is_empty", False)
            parser_mismatch = observation.get("parser_mismatch", False)
            facts_dict = observation.get("facts", {})
            fact_count = observation.get("fact_count", 0)
            obs_err = observation.get("error")
        else:
            obs_status = observation.status
            exit_code = observation.exit_code
            has_findings = observation.has_findings
            is_empty = observation.is_empty
            parser_mismatch = observation.parser_mismatch
            facts_dict = observation.facts.to_dict()
            fact_count = observation.facts.total_facts_count()
            obs_err = observation.error

        # 1. Hard Timeout Evaluation
        if obs_status == "timeout" or exit_code == 124:
            return CritiqueResult(
                has_progress=False,
                status="no_progress",
                score=0.0,
                critique=(
                    f"Node #{node_id} ({capability}) timed out executing '{tool_id}'. "
                    f"Process was terminated before capturing useful findings."
                ),
                new_facts_count=0,
                is_stagnant=True,
                is_circular=False,
                recommendation="retry" if attempt_number < 3 else "fail",
                suggested_action="Increase timeout budget or switch to a faster/lighter alternative tool.",
                evaluated_node_id=node_id,
                evaluated_capability=capability,
            )

        # 2. Execution Crash / Non-zero Exit with 0 Facts
        if exit_code != 0 and fact_count == 0:
            return CritiqueResult(
                has_progress=False,
                status="failed",
                score=0.0,
                critique=(
                    f"Node #{node_id} failed with exit code {exit_code}. "
                    f"Error diagnostic: {obs_err or 'Non-zero exit with no extracted facts'}."
                ),
                new_facts_count=0,
                is_stagnant=True,
                is_circular=False,
                recommendation="retry" if attempt_number < 3 else "fail",
                suggested_action="Repair execution arguments against tool schema or select alternate tool.",
                evaluated_node_id=node_id,
                evaluated_capability=capability,
            )

        # 3. Parser Mismatch without Recovery
        if parser_mismatch and fact_count == 0:
            return CritiqueResult(
                has_progress=False,
                status="no_progress",
                score=0.1,
                critique=(
                    f"Parser mismatch on node #{node_id} ({tool_id}): "
                    f"Adapter could not parse output and heuristic extraction found zero valid facts."
                ),
                new_facts_count=0,
                is_stagnant=True,
                is_circular=False,
                recommendation="switch_tool" if attempt_number < 3 else "fail",
                suggested_action="Switch to an alternate tool with structured JSON/XML output or verify command syntax.",
                evaluated_node_id=node_id,
                evaluated_capability=capability,
            )

        # 4. Circular / Repetitive State Evaluation
        is_circular = self._check_circular(facts_dict, previous_observations)
        if is_circular:
            return CritiqueResult(
                has_progress=False,
                status="no_progress",
                score=0.2,
                critique=(
                    f"Circular state detected on node #{node_id}: Observation yielded identical facts "
                    f"to a prior execution without providing any new delta or findings."
                ),
                new_facts_count=0,
                is_stagnant=True,
                is_circular=True,
                recommendation="switch_tool" if attempt_number < 3 else "fail",
                suggested_action="Switch tool candidate or modify scan scope/parameters to escape loop.",
                evaluated_node_id=node_id,
                evaluated_capability=capability,
            )

        # 5. Capability-Specific Evaluation
        cap_eval = self._evaluate_capability_progress(capability, facts_dict, is_empty, exit_code)
        if not cap_eval["has_progress"]:
            return CritiqueResult(
                has_progress=False,
                status="no_progress",
                score=cap_eval["score"],
                critique=cap_eval["critique"],
                new_facts_count=0,
                is_stagnant=True,
                is_circular=False,
                recommendation="retry" if attempt_number < 3 else "fail",
                suggested_action=cap_eval["suggested_action"],
                evaluated_node_id=node_id,
                evaluated_capability=capability,
            )

        # 6. Genuine Progress Confirmed
        critique_msg = (
            f"Progress confirmed for capability '{capability}': Discovered {fact_count} new structured fact(s). "
            f"Successfully advanced task graph toward goal '{plan_goal[:60]}...'."
        )

        return CritiqueResult(
            has_progress=True,
            status="progress",
            score=0.95,
            critique=critique_msg,
            new_facts_count=fact_count,
            is_stagnant=False,
            is_circular=False,
            recommendation="advance",
            suggested_action=None,
            evaluated_node_id=node_id,
            evaluated_capability=capability,
        )

    def _check_circular(
        self,
        current_facts: Dict[str, Any],
        previous_observations: List[Dict[str, Any]],
    ) -> bool:
        """Determines if the current facts are completely identical to any prior observation."""
        if not previous_observations or not current_facts:
            return False

        cur_ports = sorted(str(p.get("port")) for p in current_facts.get("ports", []))
        cur_endpoints = sorted(str(e.get("path", e.get("url", ""))) for e in current_facts.get("endpoints", []))
        cur_vulns = sorted(str(v.get("id")) for v in current_facts.get("vulnerabilities", []))

        # Only evaluate non-trivial results for circularity
        if not cur_ports and not cur_endpoints and not cur_vulns:
            return False

        for prev in previous_observations:
            prev_facts = prev.get("facts", {})
            prev_ports = sorted(str(p.get("port")) for p in prev_facts.get("ports", []))
            prev_endpoints = sorted(str(e.get("path", e.get("url", ""))) for e in prev_facts.get("endpoints", []))
            prev_vulns = sorted(str(v.get("id")) for v in prev_facts.get("vulnerabilities", []))

            if cur_ports == prev_ports and cur_endpoints == prev_endpoints and cur_vulns == prev_vulns:
                return True

        return False

    def _evaluate_capability_progress(
        self,
        capability: str,
        facts: Dict[str, Any],
        is_empty: bool,
        exit_code: int,
    ) -> Dict[str, Any]:
        """
        Validates whether the extracted facts satisfy the semantic expectations
        of the capability node.
        """
        ports = facts.get("ports", [])
        endpoints = facts.get("endpoints", [])
        vulns = facts.get("vulnerabilities", [])
        creds = facts.get("credentials", [])
        dns = facts.get("dns_records", [])

        # Network Port Scan
        if any(k in capability for k in ["port_scan", "network_port_scan"]):
            if len(ports) > 0:
                return {"has_progress": True, "score": 0.95}
            elif is_empty:
                return {
                    "has_progress": False,
                    "score": 0.2,
                    "critique": "Port scan completed with zero open ports discovered on target. Task graph has not progressed.",
                    "suggested_action": "Expand port range (e.g. -p- or top-1000) or check target connectivity with ping/SYN probe.",
                }

        # Web Directory Enumeration / Fuzzing
        if any(k in capability for k in ["directory", "fuzz", "endpoint"]):
            if len(endpoints) > 0:
                return {"has_progress": True, "score": 0.95}
            elif is_empty:
                return {
                    "has_progress": False,
                    "score": 0.25,
                    "critique": "Directory enumeration completed without discovering any reachable web paths or endpoints.",
                    "suggested_action": "Switch wordlist (e.g. dirbuster common or raft) or add file extensions (-x php,html,js).",
                }

        # Vulnerability / Injection Scan
        if any(k in capability for k in ["vulnerability", "sql", "sqli", "exploit"]):
            if len(vulns) > 0:
                return {"has_progress": True, "score": 1.0}
            elif is_empty or exit_code != 0:
                return {
                    "has_progress": False,
                    "score": 0.3,
                    "critique": "Vulnerability probe completed without identifying vulnerable parameters or confirmed security flaws.",
                    "suggested_action": "Verify injection target parameter, increase test level/risk, or run alternative web scanner.",
                }

        # Credential Testing
        if any(k in capability for k in ["credential", "password", "brute"]):
            if len(creds) > 0:
                return {"has_progress": True, "score": 1.0}
            elif is_empty or exit_code != 0:
                return {
                    "has_progress": False,
                    "score": 0.3,
                    "critique": "Credential testing completed with 0 successful logins recovered.",
                    "suggested_action": "Verify credentials wordlist, target service port, or rate-limiting thresholds.",
                }

        # DNS / Recon
        if any(k in capability for k in ["dns", "whois", "subdomain"]):
            if len(dns) > 0 or len(facts.get("hosts", [])) > 0 or facts.get("metadata"):
                return {"has_progress": True, "score": 0.90}
            elif is_empty:
                return {
                    "has_progress": False,
                    "score": 0.2,
                    "critique": "Reconnaissance query returned 0 records or hostnames for target domain.",
                    "suggested_action": "Verify domain name syntax or query authoritative DNS servers directly.",
                }

        # Host Live Detection / Connectivity / Diagnostics
        if any(k in capability for k in ["live", "host", "ping", "diagnostic", "boundary"]):
            if len(facts.get("hosts", [])) > 0 or facts.get("metadata", {}).get("system_healthy") or facts.get("metadata", {}).get("boundary_verified"):
                return {"has_progress": True, "score": 0.95}

        # Generic / Unknown Capability
        total_facts = (
            len(facts.get("hosts", []))
            + len(ports)
            + len(endpoints)
            + len(facts.get("technologies", []))
            + len(vulns)
            + len(creds)
            + len(dns)
        )
        if total_facts > 0:
            return {"has_progress": True, "score": 0.85}

        return {
            "has_progress": False,
            "score": 0.15,
            "critique": f"Capability '{capability}' execution completed without yielding any structured facts or progress.",
            "suggested_action": "Review command parameters or select an alternate specialized tool.",
        }


# Global singleton
critic = Critic()
